<div class="panel panel-default">
    <div class="panel-heading">Lista de Acessos do Grupo <strong><?php echo $this->userGroup['name'] ?></strong><a title="Voltar para listagem" href="<?php echo $this->basePath ?>admin/user-group/list-items" class="btn btn-info btn-xs pull-right"><?php echo $this->icon('arrow-circle-left') ?> Voltar para Listagem</a></div>
    <div class="panel-body">
        <?php echo $this->form()->openTag('fm-user-group-access', ['method' => 'post', 'action' => $this->basePath . 'admin/user-group/list-access', 'class' => 'form-inline', 'role' => 'form']) ?>
        <fieldset>
            <?php foreach ($this->acessos as $modulo): ?>

                <div class='panel panel-default panel-collapse'>
                    <div class='panel-heading'><?php echo $modulo['name'] ?></div>
                    <div class='panel-body'>
                        <?php foreach ($modulo['submodules'] as $submodulo): ?>
                            <fieldset class='fieldset-border access-items'>
                                <legend><?php echo $submodulo['name'] ?></legend>
                                <?php foreach ($submodulo['access'] as $acesso): ?>
                                    <?php //xd($modulo, $submodulo, $acesso) ?>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="access[<?php echo $acesso['cod'] ?>]"> <?php echo $acesso['name'] ?>
                                        </label>
                                    </div>
                                <?php endforeach; ?>
                            </fieldset>
                        <?php endforeach; ?>
                    </div>
                </div>

            <?php endforeach; ?>

            <?php echo $this->form()->submitSave()->formGroup('col-xs-12', '', 'col-xs-12') ?>
        </fieldset>
        <?php echo $this->form()->closeTag() ?>
    </div>
    <?php echo $this->dg ?>
</div>