<?php if ($this->userLogged): ?>
    <?php
    $session = new \Kf\System\Session('system');
    ?>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath ?>"></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="<?php echo $this->basePath ?>admin/index/index">Painel Administrativo</a>
                    </li>
                    
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('user') ?> &nbsp;Usuários</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>admin/user/new-item"><?php echo $this->icon('plus-circle') ?> &nbsp;Novo Usuário</a></li>
                                    <li><a href="<?php echo $this->basePath ?>admin/user/list-items"><?php echo $this->icon('list-alt') ?> &nbsp;Ver Usuários</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('users') ?> &nbsp;Grupos de Usuários</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>admin/user-group/new-item"><?php echo $this->icon('plus-circle') ?> &nbsp;Novo Grupo de Usuários</a></li>
                                    <li><a href="<?php echo $this->basePath ?>admin/user-group/list-items"><?php echo $this->icon('list-alt') ?> &nbsp;Ver Grupos de Usuários</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('bars') ?> &nbsp;Menus</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>admin/menu/list-items"><?php echo $this->icon('list-alt') ?> &nbsp;Ver Menus</a></li>
                                    <li><a href="<?php echo $this->basePath ?>admin/menu/new-item"><?php echo $this->icon('plus-circle') ?> &nbsp;Novo Menu</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('lock') ?> &nbsp;Acessos</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>admin/access/list-items"><?php echo $this->icon('list-alt') ?> &nbsp;Ver Acessos</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">RH <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('institution') ?> &nbsp;Funcionários</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>main/funcionarios/new-item"><?php echo $this->icon('plus-circle') ?> &nbsp;Novo Funcionário</a></li>
                                    <li><a href="<?php echo $this->basePath ?>main/funcionarios/list-items"><?php echo $this->icon('list-alt') ?> &nbsp;Ver Funcionários</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('trophy') ?> &nbsp;Cargos</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>main/cargos/new-item"><?php echo $this->icon('plus-circle') ?> &nbsp;Novo Cargo</a></li>
                                    <li><a href="<?php echo $this->basePath ?>main/cargos/list-items"><?php echo $this->icon('list-alt') ?> &nbsp;Ver Cargos</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kernel <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-submenu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->icon('cogs') ?> &nbsp;Gerador</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->basePath ?>admin/database/create-default-entities"><?php echo $this->icon('database') ?> &nbsp;Criar tabelas</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo isset($session->identity['name']) ? $session->identity['name'] : 'Usuário' ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->basePath ?>admin/user/profile"><?php echo $this->icon('user') ?> &nbsp;Ver Perfil</a></li>
                            <li role="presentation" class="divider"></li>
                            <li><a href="<?php echo $this->basePath ?>admin/auth/logout"><?php echo $this->icon('sign-out') ?> &nbsp;Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
