<div class="panel panel-default">
    <div class="panel-heading">
        Acessos
        <a id="btn-new-access" data-toggle="modal" data-target="#md-new-access" title="Novo Acesso" href="#" class="btn btn-info btn-xs pull-right"><?php echo $this->icon('plus-circle') ?> Novo Acesso</a>
    </div>
    <div class="panel-body">
        <div id="container">
            <div class="col-sm-8 col-xs-12 well">
                <div id="block-access"></div>
            </div>
            <div class="col-sm-4 col-xs-12">
                <?php echo $this->form()->openTag('fm-access', ['method' => 'post', 'action' => $this->basePath . 'admin/access/list-items', 'class' => 'form-horizontal', 'role' => 'form']) ?>
                <fieldset>
                    <div class="form-group">
                        <select id="controller" title="Teste" name="controller" class="show-menu-arrow col-xs-12" data-select-picker data-size="8" data-show-subtext="true" data-size="100%" data-live-search="true">
                            <option>Selecione um controller</option>
                            <?php foreach ($this->controllers as $module => $controllers): ?>
                                <optgroup label="<?php echo $module ?>">
                                    <?php foreach ($controllers as $name => $controller): ?>
                                        <option value="<?php echo $controller ?>" data-subtext="<?php echo $controller ?>"><?php echo $name ?></option>
                                    <?php endforeach ?>
                                </optgroup>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <ol id="methods" class="list-group"></ol>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<div id="md-new-access" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Novo Acesso</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->form()->openTag('fm-access', ['method' => 'post', 'action' => $this->basePath . 'admin/access/list-items', 'class' => 'form-horizontal', 'role' => 'form']) ?>
                <div class="form-group">
                    <label for="name" class="control-label col-xs-3 text-right">Nome</label>
                    <div class="col-xs-8">
                        <input type="text" placeholder="Nome do acesso" name="name" class="form-control" />
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button id="btn-save-new-access" type="button" class="btn btn-primary">Salvar</button>
            </div>
        </div>
    </div>
</div>