<select class="selectpicker" data-size="5" data-show-subtext="true">
    <option data-subtext="Heinz">Mustard</option>
    <option data-subtext="Heinz">Ketchup</option>
    <option data-subtext="Heinz">Relish</option>
    <option data-subtext="Heinz">Mustard</option>
    <option data-subtext="Heinz">Ketchup</option>
    <option data-subtext="Heinz">Relish</option>
    <option data-subtext="Heinz">Mustard</option>
    <option data-subtext="Heinz">Ketchup</option>
    <option data-subtext="Heinz">Relish</option>
    <option data-subtext="Heinz">Mustard</option>
    <option data-subtext="Heinz">Ketchup</option>
    <option data-subtext="Heinz">Relish</option>
</select>